---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-tech-patterns
  labels:
    app: stock-tech-patterns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-tech-patterns
  template:
    metadata:
      labels:
        app: stock-tech-patterns
    spec:
      containers:
        - name: stock-tech-patterns
          image: stock-tech-patterns:latest
          ports:
            - containerPort: 8080
